# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
  namespace: app-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        image: nginx:1.25
        ports:
        - containerPort: 80
        volumeMounts:
        - name: config-volume  
          mountPath: /etc/nginx/conf.d  
          readOnly: true
        - name: env-volume  
          mountPath: /etc/app-env
      volumes:
      - name: config-volume
        configMap:
          name: app-config   
          items:
          - key: app.conf   
            path: app.conf 
      - name: env-volume
        configMap:
          name: app-config
          optional: true     

